### ISSUE TITLE
Dependency on SCOOP environment variable is deprecated. 

### ISSUE THREAD

**Issue by sarvex** [plicit/scoop-search-multisource#7]
If scoop is install as per the installer command provided
```powershell
`.\install.ps1 -ScoopDir 'D:\Applications\Scoop' -ScoopGlobalDir 'F:\GlobalScoopApps' -NoProxy`
```
Scoop Search Multisource cannot find the buckets directories as the SCOOP environment variable is not available.

Current approach is to find the scoop home using the following command 
```powershell
if (!$env:SCOOP_HOME) { $env:SCOOP_HOME = Convert-Path (scoop prefix scoop) }
```

**Comment by plicit** [comment]
Thank you for your detailed bug report!  I can't seem to find any mention of SCOOP_HOME in Scoop's code, though I do see some github Issues that mention it.

Can you point to where the code you quoted comes from?

This is what I have been using:

https://github.com/ScoopInstaller/Scoop/blob/master/lib/core.ps1#L1258-L1262
```powershell
# Scoop root directory
$scoopdir = $env:SCOOP, (get_config ROOT_PATH), "$([System.Environment]::GetFolderPath('UserProfile'))\scoop" | Where-Object { -not [String]::IsNullOrEmpty($_) } | Select-Object -First 1
```

**Comment by sarvex** [comment]
> ```powershell
> if (!$env:SCOOP_HOME) { $env:SCOOP_HOME = Convert-Path (scoop prefix scoop) }
> ```

The code in present in scoop bucket [template ](https://github.com/ScoopInstaller/BucketTemplate/blob/master/bin/checkver.ps1)

**Comment by plicit** [comment]
Thanks!  When those bucket scripts execute `scoop prefix scoop`, it ultimately executes the code that I quoted to resolve the $scoopdir (aka rootPath), so there must be some other reason why it is not resolving properly on your system.

Can you give me your debug output?  e.g. run:

`scoops.exe -debug zxcv`

You can replace your username or anything you are not comfortable sharing, but I'm interested in the `CONFIG` value on your system and which ones do not exist for you.  (the "zxcv" is an arbitrary search string with 0 results)

FWIW, the resolution order for scoopdir is: (in cmd.exe format)

1. `%SCOOP%`
2. rootPath in `%XDG_CONFIG_HOME%\scoop\config.json`
3. rootPath in `%USERPROFILE%\.config\scoop\config.json`
4. `%USERPROFILE%\scoop`

**Comment by sarvex** [comment]
```powershell
VERSION: v0.1.20220804
  QUERY: (?i)zxcv
 FIELDS: name, bins
SOURCES: [{ buckets C:\Scoop\buckets} { html https://rasa.github.io/scoop-directory/by-score.html}]
 COLORS: app.name=yellow;app.version=;app.description=;source.status=;source.summary=source.status;bucket.header=;divider=;debug=light_red;app.name.installed=light_green;source.header=light_cyan;totals=light_cyan;error=light_red
 CONFIG: {"UserHome":"C:\\Users\\Yoga","ConfigHome":"C:\\Users\\Yoga\\.config","ConfigFile":"C:\\Users\\Yoga\\.config\\scoop\\config.json","ScoopDir":"C:\\Scoop","GlobalDir":"C:\\ProgramData\\scoop","CacheDir":"C:\\Scoop\\cache","NamedSourceRefs":{"active":{"Cond":"","Kind":"buckets","Path":"C:\\Scoop\\buckets"},"rasa":{"Cond":"","Kind":"html","Path":"https://rasa.github.io/scoop-directory/by-score.html"}}}
```

**Comment by sarvex** [comment]
> FWIW, the resolution order for scoopdir is: (in cmd.exe format)
> 
> 1. `%SCOOP%`
> 2. rootPath in `%XDG_CONFIG_HOME%\scoop\config.json`
> 3. rootPath in `%USERPROFILE%\.config\scoop\config.json`
> 4. `%USERPROFILE%\scoop`

If is not happening because my `%USERPROFILE%\.config\scoop\config.json` is as follows
```json
{
  "root_path": "C:\\Scoop",
  "last_update": "2023-05-19T08:22:29.9931138+05:30",
  "aria2-warning-enabled": false,
  "use_lessmsi": true,
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop"
}
```

**Comment by sarvex** [comment]
> FWIW, the resolution order for scoopdir is: (in cmd.exe format)
> 
> 1. `%SCOOP%`
> 2. rootPath in `%XDG_CONFIG_HOME%\scoop\config.json`
> 3. rootPath in `%USERPROFILE%\.config\scoop\config.json`
> 4. `%USERPROFILE%\scoop`

If is not happening because my '%USERPROFILE%\.config\scoop\config.json' is as follows

**Comment by plicit** [comment]
Thank you!  Your config.json was exactly what I needed to see.  I was using the wrong key names for config.json (it should be snake_case instead of camelCase).  

I pushed out an update.  Please let me know if it works for you. :)
